config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'calendars#index', current_date: Date.today, next_or_prev: 0
  resources :users, only: [:index, :update, :show] do
    collection do
       get :search
    end
    resources :lessons, only: [:index] do
      resources :user_owned_lessons, only:[:new, :create, :update]
    end
    resources :exams, only: [:index] do
      resources :user_owned_exams, only:[:new, :create, :update]
    end
  end
  resources :places,   only: [:index, :create, :edit, :update, :destroy]
  resources :lessons,  only: [:index, :edit, :new, :create, :update] do
    collection do
       get :search
    end
  end
  resources :exams,    only: [:index]
  resources :boats,    only: [:index, :new, :create, :edit, :update, :destroy]

  # calendars_controller
  get 'calendar/:current_date/:next_or_prev/', to: 'calendars#index', as: 'calendar'
  post  'day_details/:current_date',    to: 'day_details#create', as: 'day_details'
  patch 'day_detail/:id/:current_date', to: 'day_details#update', as: 'day_detail'

end

app/models/user.rb
class User < ApplicationRecord

  has_many :user_owned_lessons,       dependent: :destroy
  has_many :user_owned_exams,      dependent: :destroy
  has_many :user_teaching_lessons, dependent: :destroy

  has_many :taken_lessons,    through: :user_owned_lessons,    source: :lesson
  has_many :taken_exams,      through: :user_owned_exams,      source: :exam
  has_many :teaching_lessons, through: :user_teaching_lessons, source: :lesson

  has_many :holidays,              dependent: :destroy

  # For friendships between users
  has_and_belongs_to_many :friendships, class_name: "User", join_table: :friendships, foreign_key: :user_id, association_foreign_key: :friend_user_id

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :trackable

  enum gender_type: {男:0, 女:1}
  
  # validation
  validates  :name,      presence: true
  validates  :email,     presence: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    set_page_name("受講生検索")
    @users = User.order(updated_at: :desc).limit(20)
  end

  def search
    if params[:keyword] == "all"
      @users = User.all
    else
      #漢字 or ふりがな 検索
      @users = User.where('name LIKE ?',"%#{params[:keyword]}%").or(User.where('name_furigana LIKE ?',"%#{params[:keyword]}%")).reverse_order
    end
    #jbuilderを返す
    render json: @users
  end

  def show
    # 選択したuserを表示
    @user = User.find(params[:id])
    @user_owned_lessons = @user.user_owned_lessons.includes(:lesson)
    @user_owned_exams   = @user.user_owned_exams.includes(:exam)
    set_page_name(@user.name)
  end

  def update
    @user = User.find(params[:id])
    # updateできたら
    if @user.update(user_params)
      render json: @user
    else
      # バリデーションに合わせてエラーをjsonで返す
      if @user.errors
        errors = []
        @user.errors.messages.each do |key, value|
          error = key.to_s + value[0]
          errors << error
        end
        render json: {errors: errors}
      end
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :name_furigana, :former_name, :former_name_furigana, :gender, :birth, :nationality, :permanent_address, :former_permanent_address, :license_number, :license_expiration_date, :license_status, :phone_number, :phone_number2, :postal_code, :address, :postal_code2, :address2, :remark)
  end
end

app/views/users/_taken_exam.html.haml
.TakenExam
  .TakenExam__ExamInfo
    .TakenExam__ExamInfo
    .TakenExam__ExamInfo
  .TakenExam__OwnedInfo
    .TakenExam__OwnedInfo__Group1
      .TakenExam__OwnedInfo__Group1Reexam
      .TakenExam__OwnedInfo__Group1Shintaikensa
      .TakenExam__OwnedInfo__Group1ExamTicket
      .TakenExam__OwnedInfo__Group1ExamNumber
      .TakenExam__OwnedInfo__Group1Pass_or_fail
    .TakenExam__OwnedInfoPayment
    .TakenExam__OwnedInfoRemark
    .TakenExam__OwnedInfoUpdatedAt

app/views/users/_user.html.haml
.UserSearch__ListAddedUser
  %a.UserSearch__ListAddedUserLink{href: "users/#{user.id}"}
    =user.name
    =user.name_furigana

app/views/users/_user_info.html.haml
.UserInfo
  =form_with(model: @user, url: user_path, method: :patch, id: "user-update-form") do |f|
    .UserInfo__Group1
      .UserInfo__Group1__Info1
        .UserInfo__Group1__Info1Kanji
          =f.label :name, "氏名"
          =f.text_field :name
        .UserInfo__Group1__Info1Furigana
          =f.label :name_furigana, "フリガナ"
          =f.text_field :name_furigana
        -# .UserInfo__Group1__Info1FormerKanji
        -#   田中太郎
        -# .UserInfo__Group1__Info1FormerFurigana
        -#   たなかたろう
      .UserInfo__Group1__Info2
        .UserInfo__Group1__Info2Gender
          =f.label :gender, "男", class: "UserInfo__Group1__Info2GenderMale"
          =f.radio_button :gender, 0
          =f.label :gender, "女", class: "UserInfo__Group1__Info2GenderFemale"
          =f.radio_button :gender, 1
        .UserInfo__Group1__Info2Nationality
          =f.label :nationality, "国籍"
          =f.text_field :nationality, class: "UserInfo__Group1__Info2NationalityForm"
        .UserInfo__Group1__Info2Birth
          =f.label :birth, "生年月日"
          .UserInfo__Group1__Info2BirthSelect
            =date_select_ja(f.date_select :birth, start_year: 1940)
      .UserInfo__Group1__Info3
        .UserInfo__Group1__Info3LicenseStatus
          =f.label :license_status, "免許種別"
          =f.text_field :license_status
        .UserInfo__Group1__Info3LicenseExpiration
          =f.label :license_expiration_date, "有効期限"
          =date_select_ja(f.date_select :license_expiration_date)
        .UserInfo__Group1__Info3LicenseNumber
          =f.label :license_number, "免許番号"
          =f.number_field :license_number
    .UserInfo__Group2
      .UserInfo__Group2__Info1
        .UserInfo__Group2__Info1PhoneNumber
          =f.label :phone_number, "電話番号"
          =f.telephone_field :phone_number
        .UserInfo__Group2__Info1PhoneNumber2
          =f.label :phone_number2, "電話番号2"
          =f.telephone_field :phone_number2
        .UserInfo__Group2__Info1Email
          =f.label :email, "Eメール"
          =f.email_field :email
      .UserInfo__Group2__Info2
        .UserInfo__Group2__Info2PostalCode
          =f.label :postal_code, "郵便番号"
          =f.number_field :postal_code
        .UserInfo__Group2__Info2PermanentAddress
          =f.label :permanent_address, "本籍地"
          =f.text_field :permanent_address
        .UserInfo__Group2__Info2FormerPermanentAddress
          =f.label :former_permanent_address, "旧本籍地"
          =f.text_field :former_permanent_address
        .UserInfo__Group2__Info2Address
          =f.label :address, "住所"
          =f.text_area :address
      .UserInfo__Group2__Info3
        .UserInfo__Group2__Info3PostalCode2
          =f.label :postal_code2, "郵便番号2"
          =f.number_field :postal_code2
        .UserInfo__Group2__Info3Address2
          =f.label :address2, "住所2"
          =f.text_area :address2
      .UserInfo__Group2__Info4
        .UserInfo__Group2__Info4Remark
          =f.label :remark, "備考"
          =f.text_area :remark

    .UserInfo__Group3
      .UserInfo__Group3__Info1
        .UserInfo__Group3__Info1Admin
          =f.label :admin, "管理者"
          =f.check_box :admin
        .UserInfo__Group3__Info1Teacher
          =f.label :teacher, "講師"
          =f.check_box :teacher
      .UserInfo__Group3__Info2

app/views/users/_user_owned_exam.html.haml
-if controller.action_name == "new" ##newアクションの場合
  .UserOwnedExam
    =form_for( user_owned_exam, url: user_exam_user_owned_exams_path(params[:user_id], params[:exam_id]) ) do |f|
      .UserOwnedExam__Group1
        .UserOwnedExam__Group1Payment
          =f.label :payment_confirmation, "入金"
          =f.check_box :payment_confirmation
        .UserOwnedExam__Group1UpdatedAt
          =f.label :updated_at, "最終更新日"
          =simple_time(user_owned_exam.updated_at) if user_owned_exam.updated_at?
      .UserOwnedExam__Group2
        .UserOwnedExam__Group2ReExamStatus
          =f.label :re_exam_status, "再試験情報"
          %select{id: "re_exam_status"}
            %option{value:""}
            %option{value:"0"}不合格で再試
            %option{value:"1"}キャンセルで再試
        .UserOwnedExam__Group2Shintaikensa
          =f.label :shintaikensa_status, "身体検査"
          %select{id: "shintaikensa_status"}
            %option{value:""}選択してください
            %option{value:"0"}要
            %option{value:"1"}不要
            %option{value:"1"}証明書あり
      .UserOwnedExam__Group3
        .UserOwnedExam__Group3ExamTicket
          =f.label :exam_ticket, "受験票受け渡し"
          =f.check_box :exam_ticket
        .UserOwnedExam__Group3ExamNumber
          =f.label :exam_number, "受験番号"
          =f.number_field :exam_number
      .UserOwnedExam__Group4
        .UserOwnedExam__Group4Pass_or_fail
          =f.label :pass_or_fail, "合否"
          %select{id: "pass_or_fail"}
            %option{value:""}種類を選ぶ
            %option{value:"0"}合格
            %option{value:"1"}不合格
            %option{value:"2"}キャンセル
        .UserOwnedExam__Group4Remark
          =f.label :remark, "備考"
          =f.text_area :remark
      .UserOwnedExam__Submit
        =f.submit :登録
-else  # それ以外のアクション
  .UserOwnedList__ExamsList__Each
    =render partial: user_owned_exam.exam
    .UserOwnedExam
      /jsで、変更箇所の背景色を変える場所を特定するために、formタグのidにuser_owned_examのidを入れている
      /同様の理由で、各input,textarea,selectタグのdata属性に、user_owned_examのidを入れている
      =form_with(model: user_owned_exam, url: user_exam_user_owned_exam_path(user_owned_exam.user.id, user_owned_exam.exam.id, user_owned_exam.id), method: :patch , id: "user_owned_exam#{user_owned_exam.id}") do |f|
        .UserOwnedExam__Group1
          .UserOwnedExam__Group1Payment
            =f.label :payment_confirmation, "入金"
            =f.check_box :payment_confirmation, data:{id: user_owned_exam.id}
          .UserOwnedExam__Group1UpdatedAt
            =f.label :updated_at, "最終更新日"
            =simple_time(user_owned_exam.updated_at) if user_owned_exam.updated_at?
        .UserOwnedExam__Group2
          .UserOwnedExam__Group2ReExamStatus
            =f.label :re_exam_status, "再試験情報"
            %select{id: "re_exam_status", data:{id: user_owned_exam.id}}
              %option{value:""}
              %option{value:"0"}不合格で再試
              %option{value:"1"}キャンセルで再試
          .UserOwnedExam__Group2Shintaikensa
            =f.label :shintaikensa_status, "身体検査"
            %select{id: "shintaikensa_status", data:{id: user_owned_exam.id}}
              %option{value:""}選択してください
              %option{value:"0"}要
              %option{value:"1"}不要
              %option{value:"1"}証明書あり
        .UserOwnedExam__Group3
          .UserOwnedExam__Group3ExamTicket
            =f.label :exam_ticket, "受験票受け渡し"
            =f.check_box :exam_ticket, data:{id: user_owned_exam.id}
          .UserOwnedExam__Group3ExamNumber
            =f.label :exam_number, "受験番号"
            =f.number_field :exam_number, data:{id: user_owned_exam.id}
        .UserOwnedExam__Group4
          .UserOwnedExam__Group4Pass_or_fail
            =f.label :pass_or_fail, "合否"
            %select{id: "pass_or_fail", data:{id: user_owned_exam.id}}
              %option{value:""}
              %option{value:"0"}合格
              %option{value:"1"}不合格
              %option{value:"2"}キャンセル
          .UserOwnedExam__Group4Remark
            =f.label :remark, "備考"
            =f.text_area :remark, data:{id: user_owned_exam.id}
        .UserOwnedExam__Submit

app/views/users/_user_owned_lesson.html.haml
-if controller.action_name == "new" ##newアクションの場合
  .UserOwnedLesson
    =form_for user_owned_lesson, url: user_lesson_user_owned_lessons_path(params[:user_id], params[:lesson_id]) do |f|
      .UserOwnedLesson__Group1
        .UserOwnedLesson__Group1Payment
          =f.label :payment_confirmation, "入金"
          =f.check_box :payment_confirmation
        .UserOwnedLesson__Group1UpdatedAt
          =f.label :updated_at, "最終更新日"
          =simple_time(user_owned_lesson.updated_at) if user_owned_lesson.updated_at?
      .UserOwnedLesson__Remark
        =f.label :remark, "備考"
        =f.text_area :remark
      .UserOwnedLesson__Submit
        =f.submit :登録
-else  # それ以外のアクション
  .UserOwnedList__LessonsList__Each
    =render partial: user_owned_lesson.lesson
    .UserOwnedLesson
      /jsで、変更箇所の背景色を変える場所を特定するために、formタグのidにuser_owned_lesonのidを入れている
      /同様の理由で、各input,textarea,selectタグのdata属性に、user_owned_lessonのidを入れている
      =form_with(model: user_owned_lesson, url: user_lesson_user_owned_lesson_path(user_owned_lesson.user.id, user_owned_lesson.lesson.id, user_owned_lesson.id), method: :patch, id: "user_owned_lesson#{user_owned_lesson.id}") do |f|
        .UserOwnedLesson__Group1
          .UserOwnedLesson__Group1Payment
            =f.label :payment_confirmation, "入金"
            =f.check_box :payment_confirmation, data:{id: user_owned_lesson.id}
          .UserOwnedLesson__Group1UpdatedAt
            =f.label :updated_at, "最終更新日"
            =simple_time(user_owned_lesson.updated_at) if user_owned_lesson.updated_at?
        .UserOwnedLesson__Remark
          =f.label :remark, "備考"
          =f.text_area :remark, data:{id: user_owned_lesson.id}
        .UserOwnedLesson__Submit

app/views/users/index.html.haml
.UserSearch
  %input.UserSearch__Field{placeholder:"漢字かカタカナで検索 🔎"}
  .UserSearch__List
    =render @users

app/views/users/show.html.haml
/ 個人情報の表示
=render partial: "user_info"

.UserOwnedList
  .UserOwnedList__LessonsList
    %p 講習
    .UserOwnedList__LessonsList__NewButton
      =link_to "新規作成", user_lessons_path(params[:id])
    / 受講する講習一覧の表示
    =render partial: "user_owned_lesson", collection: @user_owned_lessons
  .UserOwnedList__ExamsList
    %p 試験
    .UserOwnedList__ExamsList__NewButton
      =link_to "新規作成", user_exams_path(params[:id])
    / 受験する試験一覧の表示
    =render partial: "user_owned_exam", collection: @user_owned_exams