config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'calendars#index', current_date: Date.today, next_or_prev: 0
  resources :users, only: [:index, :update, :show] do
    collection do
       get :search
    end
    resources :lessons, only: [:index] do
      resources :user_owned_lessons, only:[:new, :create, :update]
    end
    resources :exams, only: [:index] do
      resources :user_owned_exams, only:[:new, :create, :update]
    end
  end
  resources :places,   only: [:index, :create, :edit, :update, :destroy]
  resources :lessons,  only: [:index, :edit, :new, :create, :update] do
    collection do
       get :search
    end
  end
  resources :exams,    only: [:index]
  resources :boats,    only: [:index, :new, :create, :edit, :update, :destroy]

  # calendars_controller
  get 'calendar/:current_date/:next_or_prev/', to: 'calendars#index', as: 'calendar'
  post  'day_details/:current_date',    to: 'day_details#create', as: 'day_details'
  patch 'day_detail/:id/:current_date', to: 'day_details#update', as: 'day_detail'

end

app/views/shared/_flash_message.html.haml
.FlashMessage
  %p.FlashMessage__notice= notice
  %p.FlashMessage__alert= alert

app/views/shared/_navbar.html.haml
.Navbar
  .Navbar__Main
    .Navbar__MainInfo
      .Navbar__MainInfoCurrentPage
        =@page
        -if controller.controller_name == "calendars"
          =link_to "<", calendar_path(@current_date, "prev")
          =link_to ">", calendar_path(@current_date, "next")
    .Navbar__MainGroup1
      =link_to "個人", users_path, class:"Navbar__MainGroup1Kojin"
    .Navbar__MainGroup2
      =link_to "カレンダー", calendar_path(Date.today, 0), class:"Navbar__MainGroup2Calendar"
    .Navbar__MainGroup3
      =link_to "講習　登録",  new_lesson_path, class:"Navbar__MainGroup3NewLesson"
      =link_to "講習　検索",  search_lessons_path, class:"Navbar__MainGroup3LessonSearch"
      .Navbar__MainGroup3LessonJitugi
        実技
      .Navbar__MainGroup3LessonTokusyu
        特殊
    .Navbar__MainGroup4
      .Navbar__MainGroup4Exam12kyuu
        1・2級
        %br
        試験
      .Navbar__MainGroup4ExamTokusyu
        特殊試験
    .Navbar__MainGroup5
      .Navbar__MainGroup5RxLessonKousin
        更新
      .Navbar__MainGroup5RxLessonSikkou
        失効
  =render partial: "shared/flash_message"