config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'calendars#index', current_date: Date.today, next_or_prev: 0
  resources :users, only: [:index, :update, :show] do
    collection do
       get :search
    end
    resources :lessons, only: [:index] do
      resources :user_owned_lessons, only:[:new, :create, :update]
    end
    resources :exams, only: [:index] do
      resources :user_owned_exams, only:[:new, :create, :update]
    end
  end
  resources :places,   only: [:index, :create, :edit, :update, :destroy]
  resources :lessons,  only: [:index, :edit, :new, :create, :update] do
    collection do
       get :search
    end
  end
  resources :exams,    only: [:index]
  resources :boats,    only: [:index, :new, :create, :edit, :update, :destroy]

  # calendars_controller
  get 'calendar/:current_date/:next_or_prev/', to: 'calendars#index', as: 'calendar'
  post  'day_details/:current_date',    to: 'day_details#create', as: 'day_details'
  patch 'day_detail/:id/:current_date', to: 'day_details#update', as: 'day_detail'

end

app/models/exam.rb
class Exam < ApplicationRecord
  belongs_to :place
  has_many   :user_owned_exams
  has_many   :users, through: :user_owned_exams
end

app/controllers/exams_controller.rb
class ExamsController < ApplicationController

  def index
    @exams = Exam.order(updated_at: :desc).limit(20)
    #jbuilderを返す
    respond_to do |format|
      format.html
      format.json do
        # user_owned_examを作成する際に必要なuser_idをjbuilderへ受け渡す
        @user_id = params[:user_id]
        #date and type 検索
        if    params[:date] != "" && params[:type_number] != "" && params[:announcement_date] != ""
          @exams = Exam.where(date: params[:date]).where(type_number: params[:type_number]).where(announcement_date: params[:announcement_date])
        elsif params[:date] != "" && params[:type_number] != "" && params[:announcement_date] == ""
          @exams = Exam.where(date: params[:date]).where(type_number: params[:type_number])
        elsif params[:date] != "" && params[:type_number] == "" && params[:announcement_date] != ""
          @exams = Exam.where(date: params[:date]).where(announcement_date: params[:announcement_date])
        elsif params[:date] == "" && params[:type_number] != "" && params[:announcement_date] != ""
          @exams = Exam.where(type_number: params[:type_number]).where(announcement_date: params[:announcement_date])
        elsif params[:date] != "" && params[:type_number] == "" && params[:announcement_date] == ""
          @exams = Exam.where(date: params[:date])
        elsif params[:date] == "" && params[:type_number] != "" && params[:announcement_date] == ""
          @exams = Exam.where(type_number: params[:type_number])
        else
          @exams = Exam.where(announcement_date: params[:announcement_date])
        end
      end
    end
  end

  def create
    Exam.create()
  end

  private
  def exam_params
    params.require[:exam].permit(:user_id, :place_id, :type_number, :date, :gg_event_id)
  end
end

app/views/exams/_exam.html.haml
-if controller.action_name == "new" || controller.action_name == "show" ##newアクションの場合(user_owned_exams#new),showアクションの時（users#show）
  .Exam--withoutlink
    .Exam__Group1
      .Exam__Group1Type
        %label 種類
        =exam_type(exam.type_number)
      .Exam__Group1Date
        %label 試験日
        =simple_date(exam.date)
    .Exam__Group2
      .Exam__Group2Place
        %label 会場名
        =exam.place.facility_name
      .Exam__Group2GGEvent
        %label Googleカレンダー
        =gg_event?(exam.gg_event_id)
    .Exam__Group3
      .Exam__Group3AnnouncementDate
        %label 合格発表日
        =simple_date(exam.announcement_date)
      .Exam__Group3Remark
        %label 備考
        =exam.remark
-else                               ##それ以外？(exams#index)の場合
  %a.Exam{href:"#{new_user_exam_user_owned_exam_path(params[:user_id], exam.id)}"}
    .Exam__Group1
      .Exam__Group1Type
        %label 種類
        =exam_type(exam.type_number)
      .Exam__Group1Date
        %label 試験日
        =simple_date(exam.date)
    .Exam__Group2
      .Exam__Group2Place
        %label 会場名
        =exam.place.facility_name
      .Exam__Group2GGEvent
        %label Googleカレンダー
        =gg_event?(exam.gg_event_id)
    .Exam__Group3
      .Exam__Group3AnnouncementDate
        %label 合格発表日
        =simple_date(exam.announcement_date)
      .Exam__Group3Remark
        %label 備考
        =exam.remark

app/views/exams/index.html.haml
.ExamSearch
  .ExamSearch__Group1
    .ExamSearch__Group1TypeField
      %select{id: "type_number"}
        %option{value:""}種類を選ぶ
        %option{value:"0"}1・2級
        %option{value:"1"}特殊
        %option{value:"2"}湖川
    .ExamSearch__Group1DateField
      %input{type:"date", name:"calendar", max:"9999-12-31", id:"date"}
    .ExamSearch__Group1AnnouncementDateField
      %input{type:"date", name:"calendar", max:"9999-12-31", id:"announcement_date"}
    .Search__Submit
      %input{type: "submit", href:"/exams/search",value: "検索"}
  .Search__List
    =render @exams