config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'calendars#index', current_date: Date.today, next_or_prev: 0
  resources :users, only: [:index, :update, :show] do
    collection do
       get :search
    end
    resources :lessons, only: [:index] do
      resources :user_owned_lessons, only:[:new, :create, :update]
    end
    resources :exams, only: [:index] do
      resources :user_owned_exams, only:[:new, :create, :update]
    end
  end
  resources :places,   only: [:index, :create, :edit, :update, :destroy]
  resources :lessons,  only: [:index, :edit, :new, :create, :update] do
    collection do
       get :search
    end
  end
  resources :exams,    only: [:index]
  resources :boats,    only: [:index, :new, :create, :edit, :update, :destroy]

  # calendars_controller
  get 'calendar/:current_date/:next_or_prev/', to: 'calendars#index', as: 'calendar'
  post  'day_details/:current_date',    to: 'day_details#create', as: 'day_details'
  patch 'day_detail/:id/:current_date', to: 'day_details#update', as: 'day_detail'

end

app/models/place.rb
class Place < ApplicationRecord
  has_many :exams
  has_many :lessons
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  def index
    @place = Place.new
    @places = Place.all
  end

  def create
    Place.create(place_params)
    redirect_to places_path
    flash[:notice] = "作成しました！"
  end

  def edit
    @place = Place.find(params[:id])
  end

  def update
    Place.update(place_params)
    redirect_to places_path
    flash[:notice] = "更新しました！"
  end

  def destroy
    Place.find(params[:id]).destroy
    redirect_to places_path
    flash[:notice] = "削除しました！"
  end

  private
  def place_params
    params.require(:place).permit(:facility_name, :address, :map_image, :url)
  end
end

app/views/places/_place.html.haml
.Place
  .Place__Group1
    .Place__Group1FacilityName
      %label 会場名
      =place.facility_name
    .Place__Group1MapImage
      %label 地図
      =place.map_image
  .Place__Group2
    .Place__Group2Address
      %label 住所
      =place.address
    .Place__Group2Url
      %label URL
      =place.url
  .Place__Update
    =link_to "編集する", edit_place_path(place.id)
  .Place__Delete
    %a#delete{data: {link: "/places/#{place.id}"}} ダブルクリックで削除

app/views/places/edit.html.haml
.PlaceIndex
  .PlaceIndex__Form
    =form_for @place, url: place_path do |f|
      .PlaceIndex__FormGroup1
        .PlaceIndex__FormGroup1__FacilityName
          =f.label :facility_name, "会場名"
          =f.text_field :facility_name
        .PlaceIndex__FormGroup1__MapImage
          =f.label :map_image, "地図の画像ファイル"
          =f.file_field :map_image
      .PlaceIndex__FormGroup2
        .PlaceIndex__FormGroup2__Address
          =f.label :address, "住所"
          =f.text_area  :address
        .PlaceIndex__FormGroup2__Url
          =f.label :url, "URL"
          =f.text_field :url
      .PlaceIndex__FormSubmit
        =f.submit "更新する"

app/views/places/index.html.haml
.PlaceIndex
  .PlaceIndex__Form
    =form_for @place, url: places_path do |f|
      .PlaceIndex__FormGroup1
        .PlaceIndex__FormGroup1__FacilityName
          =f.label :facility_name, "会場名"
          =f.text_field :facility_name
        .PlaceIndex__FormGroup1__MapImage
          =f.label :map_image, "地図の画像ファイル"
          =f.file_field :map_image
      .PlaceIndex__FormGroup2
        .PlaceIndex__FormGroup2__Address
          =f.label :address, "住所"
          =f.text_area  :address
        .PlaceIndex__FormGroup2__Url
          =f.label :url, "URL"
          =f.text_field :url
      .PlaceIndex__FormSubmit
        =f.submit "新規作成する"
  .PlaceIndex__List
    =render @places